### ISSUE TITLE
TRAC_IK::TRAC_IK’ has no member named ‘setEpsilon’ 

### ISSUE THREAD

**Issue by idarren-deng** [baxter-flowers/trac_ik_baxter#1]
Hey, dear baxter-flower team, I got an error for ik_server.cpp

 trac_ik/trac_ik_baxter/src/ik_server.cpp:141:41: error: ‘class TRAC_IK::TRAC_IK’ has no member named ‘setEpsilon’
 this->_tracik_solver->setEpsilon(tolerance);

and in trac_ik/trac_ik.hpp, it did not have a member named ‘setEpsilon’ , am I mis-configured or with wrong version of trac_ik.

**Comment by ymollard** [comment]
You must use this modified version of trac_ik instead https://github.com/baxter-flowers/trac_ik
I've added [this info to the README](https://github.com/baxter-flowers/trac_ik_baxter#download-and-compile-the-repositories).

**Comment by idarren-deng** [comment]
Noted with great thanks!
